# Generated by Django 3.0.14 on 2022-11-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbank_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldbankindicators',
            name='language',
        ),
        migrations.AlterModelTable(
            name='worldbankcountries',
            table='wb_afro_countries',
        ),
    ]
