# Generated by Django 3.0.14 on 2022-11-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbank_metadata', '0002_auto_20221121_1159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worldbankindicators',
            unique_together={('code', 'name')},
        ),
    ]
