# Generated by Django 3.0.14 on 2022-11-22 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbank_metadata', '0003_auto_20221122_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbankcountries',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter valid Latitude', regex='^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$')], verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='worldbankcountries',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter valid Longitude', regex='^[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$')], verbose_name='Longitude'),
        ),
    ]
