# Generated by Django 3.0.14 on 2022-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbank_metadata', '0004_auto_20221122_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldbankcountries',
            name='capital',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Capital City'),
        ),
        migrations.AlterUniqueTogether(
            name='worldbankcountries',
            unique_together={('code', 'name')},
        ),
    ]
