# Generated by Django 3.0.14 on 2022-11-15 18:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GHO_URLEndpointPathMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Path ID')),
                ('url', models.CharField(max_length=45, verbose_name='GHO Base URL')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Resource Path')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=300)),
                ('resource_endpoint', models.CharField(max_length=2083, verbose_name='Resource URL Endpoint')),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mapped Endpoint',
                'verbose_name_plural': 'Mapped Endpoints',
                'db_table': 'vw_ghoapi_odata_endpoint',
                'ordering': ('url',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GHOIndicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=45, verbose_name='Indicator Code')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Indicator Name')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Language')),
                ('reference', models.CharField(blank=True, default='GHO', max_length=100, null=True, verbose_name='Indicator Reference')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'gho_indicators',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GHOSpatialDimensionCountries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=45, verbose_name='Country Code')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Country Name')),
                ('dimension', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dimension Type')),
                ('parent', models.CharField(blank=True, max_length=45, null=True, verbose_name='Parent Dimension')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'gho_afro_countries',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GHOAPIConfigs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gho_url', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid URL:'https://abc.com; or http://abc.com:8000'", regex='https?:\\/\\/(?:w{1,3}\\.)?[^\\s.]+(?:\\.[a-z]+)*(?::\\d+)?(?![^<]*(?:<\\/\\w+>|\\/?>))')], verbose_name='GHO Base URL')),
                ('gho_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('gho_passkey', models.CharField(blank=True, max_length=300, null=True, verbose_name='Password')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='GHO User/Email')),
            ],
            options={
                'verbose_name': 'URL Setup',
                'verbose_name_plural': ' GHO Base URL',
                'db_table': 'gho_odatapi_configs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GHO_URLEndpointPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_endpoint', models.CharField(blank=True, max_length=250, verbose_name='Resource API Endpoint')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghometadata.GHOAPIConfigs', verbose_name='GHO Base URL')),
            ],
            options={
                'verbose_name': ' Endpoint',
                'verbose_name_plural': 'Map Endpoints',
                'db_table': 'ghoapi_path_endpoint',
                'ordering': ('url',),
                'managed': True,
            },
        ),
    ]
