# Generated by Django 3.0.14 on 2023-12-20 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2_URLEndpointPathMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Path ID')),
                ('url', models.CharField(max_length=45, verbose_name='DHIS2 URL')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=300)),
                ('endpoint', models.CharField(max_length=100, verbose_name='Resource Path')),
                ('api_endpoint', models.CharField(max_length=2083, verbose_name='Resource URL Endpoint')),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mapped API',
                'verbose_name_plural': 'Mapped API',
                'db_table': 'vw_dhis2_mapped_api_endpoint',
                'ordering': ('endpoint',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DHIS2Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15, unique=True, verbose_name='Indicator UID')),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='DHIS2', null=True, verbose_name='Indicator Description')),
                ('reference', models.CharField(blank=True, default='DHIS2', max_length=255, null=True, verbose_name='Indicator Reference')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'dhis2_indicators',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('uid', models.CharField(max_length=45, unique=True, verbose_name='OrgUnit UID')),
                ('code', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Orgunit Code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': ' Organization Units',
                'db_table': 'dhs2_orgunits',
                'ordering': ('id', 'name'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Period ID')),
                ('name', models.CharField(max_length=50, verbose_name='Period Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('type', models.SmallIntegerField(choices=[(1, 'Fixed'), (2, 'Relative')], default=1, verbose_name='Period Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Period Type',
                'verbose_name_plural': 'Period Types',
                'db_table': 'dhis2_periods',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DHIS2MainConfigs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dhis2_url', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid URL:'https://abc.com; or http://abc.com:8000'", regex='https?:\\/\\/(?:w{1,3}\\.)?[^\\s.]+(?:\\.[a-z]+)*(?::\\d+)?(?![^<]*(?:<\\/\\w+>|\\/?>))')], verbose_name='DHIS2 URL')),
                ('dhis2_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('dhis2_passkey', models.CharField(max_length=300, verbose_name='Password')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username/Email')),
            ],
            options={
                'verbose_name': 'DHIS2 Setup',
                'verbose_name_plural': 'DHIS2 Settings',
                'db_table': 'dhis2_main_configs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DHIS2_URLEndpointPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_endpoint', models.CharField(blank=True, max_length=250, verbose_name='API Endpoint')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis2metadata.DHIS2MainConfigs', verbose_name='DHIS2 URL')),
            ],
            options={
                'verbose_name': 'API Endpoint:',
                'verbose_name_plural': 'Map API Endpoints',
                'db_table': 'dhis2_api_endpoints',
                'ordering': ('url',),
                'managed': True,
            },
        ),
    ]
