# Generated by Django 3.0.14 on 2022-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15, unique=True, verbose_name='Indicator UID')),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='DHIS2', null=True, verbose_name='Indicator Description')),
                ('reference', models.CharField(blank=True, default='DHIS2', max_length=255, null=True, verbose_name='Indicator Reference')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'DHIS2 Indicators',
                'db_table': 'dhis2_indicators',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('uid', models.CharField(max_length=45, unique=True, verbose_name='DHIS2 UID')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='DHIS2 Code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'OrgUnit',
                'verbose_name_plural': 'OrgUnits',
                'db_table': 'dhs2_orgunits',
                'ordering': ('id', 'name'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Period ID')),
                ('name', models.CharField(max_length=50, verbose_name='Period Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('type', models.SmallIntegerField(choices=[(1, 'Fixed'), (2, 'Relative')], default=1, verbose_name='Period Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Period Type',
                'verbose_name_plural': 'Period Types',
                'db_table': 'dhis2_period_type',
                'ordering': ('id',),
                'managed': True,
            },
        ),
    ]
