# Generated by Django 3.0.14 on 2022-06-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('mainconfigs', '0005_auto_20220623_1604'),
        ('dhis2metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2_URLEndpointPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_endpoint', models.CharField(blank=True, max_length=250, verbose_name='API Endpoint')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainconfigs.DHIS2Configs', verbose_name='DHIS2 API URL')),
            ],
            options={
                'verbose_name': 'Map Path:',
                'verbose_name_plural': 'Path Mapping',
                'db_table': 'dhis2_path_endpoint',
                'ordering': ('url',),
                'managed': True,
            },
        ),
    ]
