# Generated by Django 3.0.14 on 2022-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0002_dhis2_urlendpointpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2_URLEndpointPathMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Path ID')),
                ('url', models.CharField(max_length=45, verbose_name='Period Type')),
                ('username', models.CharField(max_length=45, verbose_name='Data Dimension')),
                ('password', models.CharField(max_length=45, verbose_name='Organisation Unit')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Period Type')),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'API Path',
                'verbose_name_plural': 'Mapped API Path',
                'db_table': 'vw_dhis2_apipath_endpoint',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dhis2_urlendpointpath',
            options={'managed': True, 'ordering': ('url',), 'verbose_name': 'API Path:', 'verbose_name_plural': 'API Mapping'},
        ),
        migrations.AlterModelOptions(
            name='organizationunits',
            options={'managed': True, 'ordering': ('id', 'name'), 'verbose_name': 'Organization Unit', 'verbose_name_plural': 'Organization Units'},
        ),
    ]
