# Generated by Django 3.0.14 on 2022-06-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('mainconfigs', '0006_auto_20220623_1959'),
        ('dhis2metadata', '0003_auto_20220623_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhis2_urlendpointpath',
            options={'managed': True, 'ordering': ('url',), 'verbose_name': 'API Path:', 'verbose_name_plural': 'Map URLs'},
        ),
        migrations.AlterModelOptions(
            name='dhis2_urlendpointpathmapped',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'API Path', 'verbose_name_plural': 'Mapped Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='dhis2indicators',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AlterField(
            model_name='dhis2_urlendpointpath',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainconfigs.DHIS2Configs', verbose_name='DHIS2 URL'),
        ),
    ]
