# Generated by Django 3.0.14 on 2022-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0004_auto_20220624_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunits',
            options={'managed': True, 'ordering': ('id', 'name'), 'verbose_name': 'Organization Unit', 'verbose_name_plural': ' Organization Units'},
        ),
    ]
