# Generated by Django 3.0.14 on 2022-07-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0005_auto_20220628_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhis2_urlendpointpath',
            options={'managed': True, 'ordering': ('url',), 'verbose_name': 'Endpoint:', 'verbose_name_plural': 'Map Endpoints'},
        ),
    ]
