# Generated by Django 3.0.14 on 2022-11-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0006_auto_20220704_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunits',
            name='code',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Orgunit Code'),
        ),
        migrations.AlterField(
            model_name='organizationunits',
            name='uid',
            field=models.CharField(max_length=45, unique=True, verbose_name='OrgUnit UID'),
        ),
    ]
