# Generated by Django 3.0.14 on 2022-11-09 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhis2metadata', '0007_auto_20221108_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2Configs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dhis2_url', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid URL:'https://abc.com; or http://abc.com:8000'", regex='https?:\\/\\/(?:w{1,3}\\.)?[^\\s.]+(?:\\.[a-z]+)*(?::\\d+)?(?![^<]*(?:<\\/\\w+>|\\/?>))')], verbose_name='DHIS2 URL')),
                ('dhis2_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('dhis2_passkey', models.CharField(max_length=300, verbose_name='Password')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='DIMAT User/Email')),
            ],
            options={
                'verbose_name': 'DHIS2 Setup',
                'verbose_name_plural': 'DHIS2 Settings',
                'db_table': 'ahodhis2_configs',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='dhis2_urlendpointpath',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis2metadata.DHIS2Configs', verbose_name='DHIS2 URL'),
        ),
    ]
