# Generated by Django 3.0.14 on 2022-06-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhis2metadata', '0003_auto_20220623_1959'),
        # ('mainconfigs', '0006_auto_20220623_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCT_URLEndpointPathMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Path ID')),
                ('url', models.CharField(max_length=45, verbose_name='Period Type')),
                ('username', models.CharField(max_length=45, verbose_name='Data Dimension')),
                ('password', models.CharField(max_length=45, verbose_name='Organisation Unit')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Period Type')),
                ('status', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'API Path',
                'verbose_name_plural': 'Mapped API Path',
                'db_table': 'vw_dct_apipath_endpoint',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DCTLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='LocID')),
                ('location_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location ID')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='Location Code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name')),
                ('locationlevel', models.CharField(blank=True, max_length=45, null=True, verbose_name='Level')),
                ('dhis2orgunit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhis2metadata.OrganizationUnits', verbose_name='DHIS2 Orgunit')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'afro_locations',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DCTIndicators',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Indicator ID')),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='DCT indicator', null=True, verbose_name='Indicator Description')),
                ('reference', models.CharField(blank=True, default='DCT', max_length=255, null=True, verbose_name='Indicator Reference')),
                ('dhis2', models.ManyToManyField(blank=True, to='dhis2metadata.DHIS2Indicators')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'dct_indicators',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DCT_URLEndpointPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_endpoint', models.CharField(blank=True, max_length=250, verbose_name='API Endpoint')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainconfigs.DCTConfigs', verbose_name='DHIS2 API URL')),
            ],
            options={
                'verbose_name': 'API Path:',
                'verbose_name_plural': 'API Mapping',
                'db_table': 'dct_path_endpoint',
                'ordering': ('url',),
                'managed': True,
            },
        ),
    ]
