# Generated by Django 3.0.14 on 2022-06-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('mainconfigs', '0006_auto_20220623_1959'),
        ('dctmetadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dct_urlendpointpath',
            options={'managed': True, 'ordering': ('url',), 'verbose_name': 'URL Path:', 'verbose_name_plural': 'Map URLs'},
        ),
        migrations.AlterModelOptions(
            name='dct_urlendpointpathmapped',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'URL Path', 'verbose_name_plural': 'Mapped Endpoints'},
        ),
        migrations.AlterField(
            model_name='dct_urlendpointpath',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainconfigs.DCTConfigs', verbose_name='DCT URL'),
        ),
    ]
