# Generated by Django 3.0.14 on 2022-07-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0004_remove_dctindicators_dhis2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dct_urlendpointpath',
            options={'managed': True, 'ordering': ('url',), 'verbose_name': 'Map Endpoint:', 'verbose_name_plural': 'Map Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='dct_urlendpointpathmapped',
            options={'managed': False, 'ordering': ('url',), 'verbose_name': 'Mapped Endpoint', 'verbose_name_plural': 'Mapped Endpoints'},
        ),
    ]
