# Generated by Django 3.0.14 on 2022-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0006_dct_categoryoptions_dct_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='dct_categoryoptions',
            name='category',
            field=models.PositiveIntegerField(blank=True, default=29, verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='dct_categoryoptions',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dct_datasource',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Datasource ID'),
        ),
    ]
