# Generated by Django 3.0.14 on 2022-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0007_auto_20220807_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCT_Measuretype',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Datasource ID')),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='DCT Datasource', null=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, default='DCT', max_length=255, null=True, verbose_name='Data Source')),
            ],
            options={
                'verbose_name': 'Measure Type',
                'verbose_name_plural': 'Measure Types',
                'db_table': 'dct_indicator_measuretype',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
