# Generated by Django 3.0.14 on 2022-11-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0008_dct_measuretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dct_measuretype',
            name='description',
            field=models.TextField(blank=True, default='Measure Type', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dct_measuretype',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Measure ID'),
        ),
        migrations.AlterField(
            model_name='dct_measuretype',
            name='reference',
            field=models.CharField(blank=True, default='DCT', max_length=255, null=True, verbose_name='Measure Reference'),
        ),
    ]
