# Generated by Django 3.0.14 on 2022-11-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0009_auto_20221108_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dctlocations',
            name='dhis2orgunit',
        ),
    ]
