# Generated by Django 3.0.14 on 2022-11-09 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediatorConfigs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mediator_url', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="Valid URL:'https://abc.com; or http://abc.com:8000'", regex='https?:\\/\\/(?:w{1,3}\\.)?[^\\s.]+(?:\\.[a-z]+)*(?::\\d+)?(?![^<]*(?:<\\/\\w+>|\\/?>))')], verbose_name='Mediator URL')),
                ('mediator_port', models.IntegerField(default=443, verbose_name='Mediator Port')),
                ('openhim_url', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Valid URL:'https://abc.com; or http://abc.com:8000'", regex='https?:\\/\\/(?:w{1,3}\\.)?[^\\s.]+(?:\\.[a-z]+)*(?::\\d+)?(?![^<]*(?:<\\/\\w+>|\\/?>))')], verbose_name='OpenHIM URL')),
                ('openhim_port', models.IntegerField(blank=True, default=None, null=True, verbose_name='OpenHIM Port')),
                ('openhim_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('openhim_passkey', models.CharField(blank=True, max_length=300, null=True, verbose_name='Password')),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Innactive')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='DHIS2 User/Email')),
            ],
            options={
                'verbose_name': 'Server Setup',
                'verbose_name_plural': 'Server Settings',
                'db_table': 'ahomediator_configs',
                'managed': True,
            },
        ),
    ]
