# Generated by Django 3.0.14 on 2022-06-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0003_auto_20220628_1637'),
        ('schema_mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis2_queryparameters',
            name='dctindicator',
            field=models.ForeignKey(default=339, on_delete=django.db.models.deletion.CASCADE, to='dctmetadata.DCTIndicators', verbose_name='Data Dimension'),
            preserve_default=False,
        ),
    ]
