# Generated by Django 3.0.14 on 2022-06-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0004_auto_20220624_0908'),
        ('dctmetadata', '0004_remove_dctindicators_dhis2'),
        ('schema_mappings', '0002_dhis2_queryparameters_dctindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2_queryparameters',
            name='dctindicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dctmetadata.DCTIndicators', verbose_name='DCT Indicator'),
        ),
        migrations.AlterField(
            model_name='dhis2_queryparameters',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhis2metadata.DHIS2Indicators', verbose_name='DHI2 Indicator'),
        ),
    ]
