# Generated by Django 3.0.14 on 2022-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0004_remove_dctindicators_dhis2'),
        ('dhis2metadata', '0005_auto_20220628_1818'),
        ('schema_mappings', '0003_auto_20220628_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DHIS2DCT_IndicatorsMapped',
        ),
        migrations.AlterModelOptions(
            name='dhis2_queryparameters',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'Map Parameter', 'verbose_name_plural': '  Map Parameters'},
        ),
        migrations.AlterModelOptions(
            name='dhis2dct_locationsmapped',
            options={'managed': False, 'ordering': ('dct_country',), 'verbose_name': 'Country', 'verbose_name_plural': 'Mapped Countries'},
        ),
        migrations.AlterModelOptions(
            name='factsdhis2_indicators',
            options={'managed': True, 'verbose_name': 'Map Fact', 'verbose_name_plural': '  Map DHIS2 Facts'},
        ),
        migrations.AlterModelOptions(
            name='factsdhis2_indicatorsmapped',
            options={'managed': False, 'verbose_name': 'Mapped Fact', 'verbose_name_plural': ' Mapped Facts'},
        ),
        migrations.AlterModelOptions(
            name='factsdhis2_queryparametersmapped',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Parameter', 'verbose_name_plural': ' Mapped Parameters'},
        ),
        migrations.AlterUniqueTogether(
            name='dhis2_queryparameters',
            unique_together={('dctindicator', 'indicator', 'location')},
        ),
    ]
