# Generated by Django 3.0.14 on 2022-06-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema_mappings', '0005_auto_20220628_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhis2_queryparameters',
            name='period',
        ),
    ]
