# Generated by Django 3.0.14 on 2022-06-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2metadata', '0005_auto_20220628_1818'),
        ('schema_mappings', '0006_remove_dhis2_queryparameters_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2_queryparameters',
            name='periodicity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dhis2metadata.PeriodType', verbose_name='Period Type'),
        ),
    ]
