# Generated by Django 3.0.14 on 2022-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema_mappings', '0008_auto_20220704_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2DCT_IndicatorsMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Indicator ID')),
                ('dct_indicator_name', models.CharField(max_length=45, verbose_name='DCT Indicator Name')),
                ('afrocode', models.CharField(max_length=45, verbose_name='DCT Indicator Code')),
                ('dhis2_indicator', models.CharField(max_length=100, verbose_name='DHIS2 Indicator Name')),
                ('dhis_indicator_uid', models.CharField(blank=True, max_length=45, null=True, verbose_name='DHIS2 Indicator ID')),
                ('dct_indicator_id', models.PositiveIntegerField(verbose_name='DCT Indicator ID')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Mapped Indicators',
                'db_table': 'vw_dhis2dct_indicators_mapped',
                'ordering': ('dct_indicator_name',),
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='factsdhis2_indicators',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
