# Generated by Django 3.0.14 on 2022-11-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0009_auto_20221108_1523'),
        ('schema_mappings', '0009_auto_20220705_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factsdhis2_indicators',
            options={'managed': True, 'verbose_name': 'Fact', 'verbose_name_plural': '  DHIS2 Facts'},
        ),
        migrations.AlterField(
            model_name='factsdhis2_indicators',
            name='categoryoption',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Categoryoptions', verbose_name='Disaggregation Option'),
        ),
        migrations.AlterField(
            model_name='factsdhis2_indicators',
            name='datasource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Datasource', verbose_name='Datasource ID'),
        ),
        migrations.AlterField(
            model_name='factsdhis2_indicators',
            name='indicator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTIndicators', verbose_name='Indicator ID'),
        ),
        migrations.AlterField(
            model_name='factsdhis2_indicators',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTLocations', verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='factsdhis2_indicators',
            name='measuremethod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Measuretype', verbose_name='Measure Type'),
        ),
    ]
