# Generated by Django 3.0.14 on 2022-11-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0009_auto_20221108_1523'),
        ('dhis2metadata', '0007_auto_20221108_1838'),
        ('schema_mappings', '0010_auto_20221108_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factsdhis2_indicators',
            options={'managed': True, 'verbose_name': 'Fact', 'verbose_name_plural': '  Fetched Facts'},
        ),
        migrations.CreateModel(
            name='DHIS2DCT_MapOrgunitLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Location ID')),
                ('location', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTLocations', verbose_name='AFRO/Country')),
                ('orgunit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dhis2metadata.OrganizationUnits', verbose_name='Organisation Unit')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Map Countries',
                'db_table': 'dhis2_ahodimat_map_orunitlocations',
                'ordering': ('location',),
                'managed': True,
                'unique_together': {('orgunit', 'location')},
            },
        ),
    ]
