# Generated by Django 3.0.14 on 2022-11-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0011_auto_20221109_1118'),
        ('dhis2metadata', '0008_auto_20221109_1118'),
        ('schema_mappings', '0011_auto_20221108_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhis2dct_locationsmapped',
            options={'managed': False, 'ordering': ('location_name',), 'verbose_name': 'Country', 'verbose_name_plural': 'Mapped Countries'},
        ),
        migrations.AlterField(
            model_name='dhis2dct_maporgunitlocations',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTLocations', verbose_name='DCT Related Location'),
        ),
        migrations.AlterField(
            model_name='dhis2dct_maporgunitlocations',
            name='orgunit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dhis2metadata.OrganizationUnits', verbose_name='DHIS2 Organisation Unit'),
        ),
    ]
