# Generated by Django 3.0.14 on 2022-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHO_IndicatorFacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Indicator Code')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('category', models.CharField(blank=True, default=29, max_length=45, null=True, verbose_name='Disaggregation Type')),
                ('categoryoption', models.CharField(blank=True, default=29, max_length=45, null=True, verbose_name='Disaggregation Option')),
                ('numeric_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Value Received')),
                ('adjusted_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('period_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='Year')),
                ('start_period', models.DateField(blank=True, null=True, verbose_name='Start Period')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'GHO Facts',
                'verbose_name_plural': '  GHO Facts',
                'db_table': 'gho_indicator_facts_extracted',
                'managed': True,
            },
        ),
    ]
