# Generated by Django 3.0.14 on 2023-12-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dctmetadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsGHO_IndicatorsMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('indicator_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Code')),
                ('indicator_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Name')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country Name')),
                ('category', models.CharField(blank=True, default=1, max_length=200, null=True, verbose_name='Disaggrergation category')),
                ('categoryoption', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='Disaggregation Option')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('start_period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Start Period')),
                ('end_period', models.CharField(blank=True, max_length=45, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Fetched Fact',
                'verbose_name_plural': ' Fetched Facts',
                'db_table': 'vw_gho_indicators_facts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactsGHO_IndicatorsViewMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('indicator', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Indicator ID')),
                ('location', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Country ID')),
                ('datasource', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='Datasource ID')),
                ('categoryoption', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='Disaggregation Option')),
                ('measuremethod', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Measure Type')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('value_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Value Received')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('string_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='String Value')),
                ('start_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Period')),
                ('end_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
                ('status', models.CharField(blank=True, max_length=45, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mapped GHO-DCT Fact',
                'verbose_name_plural': 'Mapped GHO-DCT Facts',
                'db_table': 'vw_gho_mapped_dct_indicator_facts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GHO_IndicatorFacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Indicator Code')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('category', models.CharField(blank=True, default=29, max_length=45, null=True, verbose_name='Disaggregation Type')),
                ('categoryoption', models.CharField(blank=True, default=29, max_length=45, null=True, verbose_name='Disaggregation Option')),
                ('numeric_value', models.CharField(blank=True, max_length=45, null=True, verbose_name='Numeric Value')),
                ('adjusted_value', models.CharField(blank=True, max_length=45, null=True)),
                ('min_value', models.CharField(blank=True, max_length=45, null=True)),
                ('max_value', models.CharField(blank=True, max_length=45, null=True)),
                ('period_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='Year')),
                ('start_period', models.DateField(blank=True, null=True, verbose_name='Start Period')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
            ],
            options={
                'verbose_name': 'GHO Facts',
                'verbose_name_plural': '  GHO Facts',
                'db_table': 'gho_fetched_indicator_facts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FactsGHODCT_Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('value_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Value Received')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('string_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='String Value')),
                ('start_period', models.DateField(blank=True, null=True, verbose_name='Start Period')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('categoryoption', models.ForeignKey(default=29, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Categoryoptions', verbose_name='Disaggregation Option')),
                ('datasource', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Datasource', verbose_name='Datasource ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTIndicators', verbose_name='Indicator ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTLocations', verbose_name='Country ID')),
                ('measuremethod', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Measuretype', verbose_name='Measure Type')),
            ],
            options={
                'verbose_name': 'GHO-DCT fact',
                'verbose_name_plural': ' Map Facts',
                'db_table': 'gho_dct_mapped_indicator_facts',
                'managed': True,
                'unique_together': {('indicator', 'location', 'categoryoption', 'period')},
            },
        ),
    ]
