# Generated by Django 3.0.14 on 2022-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Value Received'),
        ),
    ]
