# Generated by Django 3.0.14 on 2022-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0002_auto_20220806_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='adjusted_value',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='end_period',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='End Period'),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='max_value',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='min_value',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='numeric_value',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Numeric Value'),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='start_period',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Start Period'),
        ),
    ]
