# Generated by Django 3.0.14 on 2022-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0003_auto_20220806_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='end_period',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='End Period'),
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='start_period',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='Start Period'),
        ),
    ]
