# Generated by Django 3.0.14 on 2022-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0004_auto_20220807_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='end_period',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='End Period'),
        ),
    ]
