# Generated by Django 3.0.14 on 2022-08-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0008_auto_20220807_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsGHO_IndicatorsMapped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('indicator_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Code')),
                ('indicator_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Name')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country Name')),
                ('category', models.CharField(blank=True, default=1, max_length=200, null=True, verbose_name='Disaggrergation category')),
                ('categoryoption', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='Disaggregation Option')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('start_period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Start Period')),
                ('end_period', models.CharField(blank=True, max_length=45, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Mapped Fact',
                'verbose_name_plural': ' Mapped Facts',
                'db_table': 'vw_gho_fact_indicators',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='gho_indicatorfacts',
            name='period',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Period'),
        ),
        migrations.CreateModel(
            name='FactsGHODCT_Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fact ID')),
                ('indicator', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Indicator ID')),
                ('location', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Country ID')),
                ('datasource', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='Datasource ID')),
                ('categoryoption', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='Disaggregation Option')),
                ('measuremethod', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Measure Type')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('value_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Value Received')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('string_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='String Value')),
                ('start_period', models.DateField(blank=True, null=True, verbose_name='Start Period')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='End Period')),
                ('period', models.CharField(blank=True, max_length=45, null=True, verbose_name='Period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Map Fact',
                'verbose_name_plural': '  Map DHIS2 Facts',
                'db_table': 'fact_ghodct_indicator_dataset',
                'managed': True,
                'unique_together': {('indicator', 'location', 'period')},
            },
        ),
    ]
