# Generated by Django 3.0.14 on 2022-08-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0009_auto_20220807_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factsgho_indicatorsmapped',
            options={'managed': False, 'verbose_name': 'Stage Fact', 'verbose_name_plural': 'GHO Data Staged'},
        ),
        migrations.AlterModelOptions(
            name='factsghodct_indicators',
            options={'managed': True, 'verbose_name': 'GHO-DCT fact', 'verbose_name_plural': '  GHO-DCT Facts'},
        ),
    ]
