# Generated by Django 3.0.14 on 2022-08-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0005_auto_20220704_1455'),
        ('gho_mappings', '0010_auto_20220807_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='indicator',
            field=models.ForeignKey(default=381, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTIndicators', verbose_name='Indicator ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='location',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCTLocations', verbose_name='Country ID'),
            preserve_default=False,
        ),
    ]
