# Generated by Django 3.0.14 on 2022-08-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0007_auto_20220807_1137'),
        ('gho_mappings', '0011_auto_20220807_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='categoryoption',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Categoryoptions', verbose_name='Disaggregation Option'),
        ),
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='datasource',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Datasource', verbose_name='Datasource ID'),
        ),
    ]
