# Generated by Django 3.0.14 on 2022-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0008_dct_measuretype'),
        ('gho_mappings', '0013_auto_20220807_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='datasource',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Datasource', verbose_name='Datasource ID'),
        ),
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='measuremethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Measuretype', verbose_name='Measure Type'),
        ),
    ]
