# Generated by Django 3.0.14 on 2022-08-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctmetadata', '0008_dct_measuretype'),
        ('gho_mappings', '0014_auto_20220807_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsghodct_indicators',
            name='measuremethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dctmetadata.DCT_Measuretype', verbose_name='Measure Type'),
        ),
    ]
