# Generated by Django 3.0.14 on 2022-11-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gho_mappings', '0016_factsgho_indicatorsviewmapped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factsgho_indicatorsmapped',
            options={'managed': False, 'verbose_name': 'Stage Fact', 'verbose_name_plural': ' Staged Facts'},
        ),
        migrations.AlterModelOptions(
            name='factsgho_indicatorsviewmapped',
            options={'managed': False, 'verbose_name': 'Map Fact', 'verbose_name_plural': 'Mapped Facts'},
        ),
        migrations.AlterModelOptions(
            name='factsghodct_indicators',
            options={'managed': True, 'verbose_name': 'GHO-DCT fact', 'verbose_name_plural': ' Map Facts'},
        ),
        migrations.AlterModelOptions(
            name='gho_indicatorfacts',
            options={'managed': True, 'verbose_name': 'GHO Facts', 'verbose_name_plural': '  Fetched Facts'},
        ),
    ]
